version: 3

tasks:
  t:
    desc: Run tests
    cmds:
      - "go test"

  cov:
    desc: Run coverage
    cmds:
      - "go test -coverprofile=cov.out ./... && go tool cover -func=cov.out"

  html:
    desc: Run coverage
    cmds:
      - "go test -coverprofile=cov.out ./... && go tool cover -html=cov.out"