// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/ctrl/ctrl.go
//
// Generated by this command:
//
//	mockgen -source=./internal/ctrl/ctrl.go -destination=mocks/mock_repos.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/JMURv/service-discovery/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceDiscoveryRepo is a mock of ServiceDiscoveryRepo interface.
type MockServiceDiscoveryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockServiceDiscoveryRepoMockRecorder
	isgomock struct{}
}

// MockServiceDiscoveryRepoMockRecorder is the mock recorder for MockServiceDiscoveryRepo.
type MockServiceDiscoveryRepoMockRecorder struct {
	mock *MockServiceDiscoveryRepo
}

// NewMockServiceDiscoveryRepo creates a new mock instance.
func NewMockServiceDiscoveryRepo(ctrl *gomock.Controller) *MockServiceDiscoveryRepo {
	mock := &MockServiceDiscoveryRepo{ctrl: ctrl}
	mock.recorder = &MockServiceDiscoveryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceDiscoveryRepo) EXPECT() *MockServiceDiscoveryRepoMockRecorder {
	return m.recorder
}

// ActivateSvc mocks base method.
func (m *MockServiceDiscoveryRepo) ActivateSvc(ctx context.Context, name, addr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateSvc", ctx, name, addr)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateSvc indicates an expected call of ActivateSvc.
func (mr *MockServiceDiscoveryRepoMockRecorder) ActivateSvc(ctx, name, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateSvc", reflect.TypeOf((*MockServiceDiscoveryRepo)(nil).ActivateSvc), ctx, name, addr)
}

// Close mocks base method.
func (m *MockServiceDiscoveryRepo) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockServiceDiscoveryRepoMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockServiceDiscoveryRepo)(nil).Close))
}

// DeactivateSvc mocks base method.
func (m *MockServiceDiscoveryRepo) DeactivateSvc(arg0 context.Context, name, addr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateSvc", arg0, name, addr)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateSvc indicates an expected call of DeactivateSvc.
func (mr *MockServiceDiscoveryRepoMockRecorder) DeactivateSvc(arg0, name, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateSvc", reflect.TypeOf((*MockServiceDiscoveryRepo)(nil).DeactivateSvc), arg0, name, addr)
}

// Deregister mocks base method.
func (m *MockServiceDiscoveryRepo) Deregister(ctx context.Context, name, addr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deregister", ctx, name, addr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deregister indicates an expected call of Deregister.
func (mr *MockServiceDiscoveryRepoMockRecorder) Deregister(ctx, name, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deregister", reflect.TypeOf((*MockServiceDiscoveryRepo)(nil).Deregister), ctx, name, addr)
}

// FindServiceByName mocks base method.
func (m *MockServiceDiscoveryRepo) FindServiceByName(ctx context.Context, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindServiceByName", ctx, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindServiceByName indicates an expected call of FindServiceByName.
func (mr *MockServiceDiscoveryRepoMockRecorder) FindServiceByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindServiceByName", reflect.TypeOf((*MockServiceDiscoveryRepo)(nil).FindServiceByName), ctx, name)
}

// ListAddrsByName mocks base method.
func (m *MockServiceDiscoveryRepo) ListAddrsByName(ctx context.Context, name string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAddrsByName", ctx, name)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAddrsByName indicates an expected call of ListAddrsByName.
func (mr *MockServiceDiscoveryRepoMockRecorder) ListAddrsByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAddrsByName", reflect.TypeOf((*MockServiceDiscoveryRepo)(nil).ListAddrsByName), ctx, name)
}

// ListNames mocks base method.
func (m *MockServiceDiscoveryRepo) ListNames(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNames", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNames indicates an expected call of ListNames.
func (mr *MockServiceDiscoveryRepoMockRecorder) ListNames(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNames", reflect.TypeOf((*MockServiceDiscoveryRepo)(nil).ListNames), ctx)
}

// ListServices mocks base method.
func (m *MockServiceDiscoveryRepo) ListServices(ctx context.Context) ([]model.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServices", ctx)
	ret0, _ := ret[0].([]model.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServices indicates an expected call of ListServices.
func (mr *MockServiceDiscoveryRepoMockRecorder) ListServices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServices", reflect.TypeOf((*MockServiceDiscoveryRepo)(nil).ListServices), ctx)
}

// Register mocks base method.
func (m *MockServiceDiscoveryRepo) Register(ctx context.Context, name, addr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, name, addr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockServiceDiscoveryRepoMockRecorder) Register(ctx, name, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockServiceDiscoveryRepo)(nil).Register), ctx, name, addr)
}
