version: 3

tasks:

  mock:
    desc: Generate mocks
    cmds:
      - mockgen -source="ctrl.go" -destination="mocks/mock_repos.go" -package=mocks

  t:
    desc: Run app
    cmds:
      - "go test"

  cov:
    desc: Run coverage
    cmds:
      - "go test -coverprofile=cov.out ./... && go tool cover -func=cov.out"

  html:
    desc: Run coverage
    cmds:
      - "go test -coverprofile=cov.out ./... && go tool cover -html=cov.out"