on:
  push:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.1'

      - name: Install dependencies
        run: go mod tidy

      - name: Install gocovmerge
        run: go install github.com/wadey/gocovmerge@latest

      - name: Run repo memory tests
        run: go test -coverprofile=repo_mem_coverage.out ./internal/repo/memory

      - name: Run controller tests
        run: go test -coverprofile=ctrl_coverage.out ./internal/ctrl

      - name: Run gRPC handler tests
        run: go test -coverprofile=grpc_hdl_coverage.out ./internal/hdl/grpc

      - name: Run HTTP handler tests
        run: go test -coverprofile=http_hdl_coverage.out ./internal/hdl/http

      - name: Merge coverage reports
        run: gocovmerge repo_mem_coverage.out ctrl_coverage.out grpc_hdl_coverage.out http_hdl_coverage.out > coverage.out

      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          coverage-file: coverage.out
          report: true
          chart: true
          amend: true
        if: |
          matrix.os == 'ubuntu-latest' &&
          github.event_name == 'push'
        continue-on-error: true